name: gym_genius
description: GymGenius - AI-Powered Fitness App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  intl: ^0.20.0
  hive_flutter: ^1.1.0
  table_calendar: ^3.1.3
  flutter_slidable: ^3.1.1
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.2.0+3
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  icons_plus: ^5.0.0
  cupertino_icons: ^1.0.8
  health: ^13.3.1
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
